=== KolonelKustard/sketchingout/xml/consequences.dtd
<!ELEMENT consequences (user, drawing)>
  <!ELEMENT user (signature?)>
    <!ELEMENT signature (#PCDATA)>
  <!ELEMENT drawing (bodypart, send_on_to?)>
    <!ELEMENT bodypart (line+)>
      <!ELEMENT line (point+)>
        <!ELEMENT point EMPTY>
        
    <!ELEMENT send_on_to EMPTY>
    
<!ATTLIST user id ID #REQUIRED>
<!ATTLIST user name CDATA #REQUIRED>
<!ATTLIST user email CDATA #REQUIRED>

<!ATTLIST bodypart part (head|body|legs|feet) #REQUIRED>

<!ATTLIST point x CDATA #REQUIRED>
<!ATTLIST point y CDATA #REQUIRED>

<!ATTLIST send_on_to email CDATA #REQUIRED>

=== KolonelKustard/sketchingout/xml/consequences.xml
<?xml version="1.0"?>
<!DOCTYPE consequences SYSTEM "consequences.dtd">

<consequences>
  <user id="unique01234" name="simondo" email="simon@bluestone.co.uk"/>
  <drawing>
    <bodypart part="head">
      <line>
        <point x="100" y="200"/>
        <point x="245" y="423"/>
        <point x="234" y="543"/>
        <point x="431" y="343"/>
      </line>
    </bodypart>
    <send_on_to email="bodger@badger.com"/>
  </drawing>
</consequences>
