=== KolonelKustard/sketchingout/server/src/main/xml/response.dtd
<!ELEMENT response (next_drawing?, gallery_drawings?, gallery_drawing?, errors?)>

  <!ELEMENT next_drawing (drawing_id, stage, locked_secs, drawing?)>
    <!ELEMENT drawing_id (#PCDATA)>
    <!ELEMENT stage (#PCDATA)>
    <!ELEMENT locked_secs (#PCDATA)>
    <!ELEMENT drawing (#PCDATA)>
    
  <!ELEMENT gallery_drawings (gallery_drawing*)>

  <!ELEMENT gallery_drawing (drawing_id, width, height, num_stages, stage_author+, anim_swf_url, pdf_url)>
    <!ELEMENT width (#PCDATA)>
    <!ELEMENT height (#PCDATA)>
    <!ELEMENT num_stages (#PCDATA)>
    <!ELEMENT stage_author (stage, name)>
      <!ELEMENT name (#PCDATA)>
    <!ELEMENT anim_swf_url (#PCDATA)>
    <!ELEMENT pdf_url (#PCDATA)>
    
  <!ELEMENT errors (error+)>
    <!ELEMENT error (src, type, message, stacktrace?)>
      <!ELEMENT src (#PCDATA)>
      <!ELEMENT type (#PCDATA)>
      <!ELEMENT message (#PCDATA)>
      <!ELEMENT stacktrace (trace+)>
        <!ELEMENT trace (#PCDATA)>

=== KolonelKustard/sketchingout/server/src/main/xml/response_gallery.xml
<?xml version="1.0"?>
<!DOCTYPE response SYSTEM "response.dtd">

<response>
  <gallery_drawings>
  
    <gallery_drawing>
      <drawing_id>10</drawing_id>
      <width>400</width>
      <height>800</height>
      <num_stages>4</num_stages>
      <stage_author>
        <stage>1</stage>
        <name>User 1</name>
      </stage_author>
      <stage_author>
        <stage>2</stage>
        <name>User 2</name>
      </stage_author>
      <stage_author>
        <stage>3</stage>
        <name>User 3</name>
      </stage_author>
      <stage_author>
        <stage>4</stage>
        <name>User 4</name>
      </stage_author>
      <anim_swf_url>http://www.sketchingout.co.uk/drawings/1.swf</anim_swf_url>
      <pdf_url>http://www.sketchingout.co.uk/drawings/1.pdf</pdf_url>
    </gallery_drawing>
    
    <gallery_drawing>
      <drawing_id>9</drawing_id>
      <width>400</width>
      <height>800</height>
      <num_stages>4</num_stages>
      <stage_author>
        <stage>1</stage>
        <name>User 1</name>
      </stage_author>
      <stage_author>
        <stage>2</stage>
        <name>User 2</name>
      </stage_author>
      <stage_author>
        <stage>3</stage>
        <name>User 3</name>
      </stage_author>
      <stage_author>
        <stage>4</stage>
        <name>User 4</name>
      </stage_author>
      <anim_swf_url>http://www.sketchingout.co.uk/drawings/1.swf</anim_swf_url>
      <pdf_url>http://www.sketchingout.co.uk/drawings/1.pdf</pdf_url>
    </gallery_drawing>
    
  </gallery_drawings>
</response>

=== KolonelKustard/sketchingout/xml/response_gallery.xml
<?xml version="1.0"?>
<!DOCTYPE response SYSTEM "response.dtd">

<response>
  <gallery_drawings>
  
    <gallery_drawing>
      <drawing_id>10</drawing_id>
      <width>400</width>
      <height>800</height>
      <num_stages>4</num_stages>
      <stage_author>
        <stage>1</stage>
        <name>User 1</name>
      </stage_author>
      <stage_author>
        <stage>2</stage>
        <name>User 2</name>
      </stage_author>
      <stage_author>
        <stage>3</stage>
        <name>User 3</name>
      </stage_author>
      <stage_author>
        <stage>4</stage>
        <name>User 4</name>
      </stage_author>
    </gallery_drawing>
    
    <gallery_drawing>
      <drawing_id>9</drawing_id>
      <width>400</width>
      <height>800</height>
      <num_stages>4</num_stages>
      <stage_author>
        <stage>1</stage>
        <name>User 1</name>
      </stage_author>
      <stage_author>
        <stage>2</stage>
        <name>User 2</name>
      </stage_author>
      <stage_author>
        <stage>3</stage>
        <name>User 3</name>
      </stage_author>
      <stage_author>
        <stage>4</stage>
        <name>User 4</name>
      </stage_author>
    </gallery_drawing>
    
  </gallery_drawings>
</response>
